import { Permit } from "./types";

function daysAgo(n: number): string {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
}

export const MOCK_PERMITS: Permit[] = [
  {
    id: "p-001",
    permitNumber: "BLD-2026-041523",
    address: "233 S Wacker Dr",
    city: "Chicago",
    state: "IL",
    zip: "60606",
    latitude: 41.8789,
    longitude: -87.6359,
    filingDate: daysAgo(1),
    description:
      "Complete HVAC system replacement for floors 12-18 of commercial office tower. Includes new rooftop units, ductwork, and building automation controls.",
    estimatedValue: 2850000,
    status: "Issued",
    trades: ["HVAC"],
    gcContact: {
      companyName: "Turner Construction Company",
      contactName: "Mike Reynolds",
      phone: "(312) 555-0142",
      email: "mreynolds@turnerconstruction.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(1),
  },
  {
    id: "p-002",
    permitNumber: "BLD-2026-041487",
    address: "401 N Michigan Ave",
    city: "Chicago",
    state: "IL",
    zip: "60611",
    latitude: 41.8902,
    longitude: -87.6238,
    filingDate: daysAgo(2),
    description:
      "Electrical service upgrade and panel replacement for 15-story mixed-use building. New 4000A main switchgear, emergency generator, and fire alarm system.",
    estimatedValue: 1750000,
    status: "Issued",
    trades: ["Electrical", "Fire Suppression"],
    gcContact: {
      companyName: "Pepper Construction",
      contactName: "Sarah Chen",
      phone: "(312) 555-0198",
      email: "schen@pepperconstruction.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(1),
  },
  {
    id: "p-003",
    permitNumber: "BLD-2026-041390",
    address: "1 N State St",
    city: "Chicago",
    state: "IL",
    zip: "60602",
    latitude: 41.8819,
    longitude: -87.6278,
    filingDate: daysAgo(3),
    description:
      "Interior buildout of new medical office space, 22,000 SF. Includes plumbing rough-in for exam rooms, specialized HVAC for clean rooms, and glass partition walls.",
    estimatedValue: 3200000,
    status: "Under Review",
    trades: ["Plumbing", "HVAC", "Glass & Glazing"],
    gcContact: {
      companyName: "Power Construction",
      contactName: "James Kowalski",
      phone: "(312) 555-0267",
      email: "jkowalski@powerconstruction.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(2),
  },
  {
    id: "p-004",
    permitNumber: "BLD-2026-041352",
    address: "550 W Adams St",
    city: "Chicago",
    state: "IL",
    zip: "60661",
    latitude: 41.8793,
    longitude: -87.6418,
    filingDate: daysAgo(3),
    description:
      "Complete roof replacement on 8-story commercial building. TPO membrane system, new insulation, and parapet wall repairs.",
    estimatedValue: 890000,
    status: "Issued",
    trades: ["Roofing"],
    gcContact: {
      companyName: "W.E. O'Neil Construction",
      contactName: null,
      phone: "(312) 555-0334",
      email: null,
      confidence: "Medium",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(3),
  },
  {
    id: "p-005",
    permitNumber: "BLD-2026-041298",
    address: "161 N Clark St",
    city: "Chicago",
    state: "IL",
    zip: "60601",
    latitude: 41.8843,
    longitude: -87.6311,
    filingDate: daysAgo(4),
    description:
      "Fire suppression system upgrade for county building. New sprinkler heads, standpipe system, and fire pump replacement.",
    estimatedValue: 1200000,
    status: "Approved",
    trades: ["Fire Suppression", "Plumbing"],
    gcContact: {
      companyName: "Bulley & Andrews",
      contactName: "Tom Andersen",
      phone: "(312) 555-0401",
      email: "tandersen@bulley.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(3),
  },
  {
    id: "p-006",
    permitNumber: "BLD-2026-041245",
    address: "225 W Randolph St",
    city: "Chicago",
    state: "IL",
    zip: "60606",
    latitude: 41.8847,
    longitude: -87.6347,
    filingDate: daysAgo(5),
    description:
      "New restaurant buildout in ground floor commercial space. Full kitchen hood and HVAC, grease trap plumbing, electrical for commercial kitchen equipment.",
    estimatedValue: 680000,
    status: "Issued",
    trades: ["HVAC", "Plumbing", "Electrical"],
    gcContact: {
      companyName: "Leopardo Companies",
      contactName: "Angela Martinez",
      phone: "(312) 555-0488",
      email: "amartinez@leopardo.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(4),
  },
  {
    id: "p-007",
    permitNumber: "BLD-2026-041201",
    address: "311 S Wacker Dr",
    city: "Chicago",
    state: "IL",
    zip: "60606",
    latitude: 41.8779,
    longitude: -87.6363,
    filingDate: daysAgo(5),
    description:
      "Structural steel reinforcement for mechanical penthouse. Adding new cooling tower support structure and equipment platforms.",
    estimatedValue: 1450000,
    status: "Under Review",
    trades: ["Structural Steel", "HVAC"],
    gcContact: {
      companyName: "Clark Construction Group",
      contactName: "David Park",
      phone: "(312) 555-0523",
      email: "dpark@clarkconstruction.com",
      confidence: "Medium",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(5),
  },
  {
    id: "p-008",
    permitNumber: "BLD-2026-041178",
    address: "330 N Wabash Ave",
    city: "Chicago",
    state: "IL",
    zip: "60611",
    latitude: 41.8882,
    longitude: -87.6268,
    filingDate: daysAgo(6),
    description:
      "Curtain wall glass replacement on south and west facades. Approximately 4,200 SF of insulated glazing units.",
    estimatedValue: 2100000,
    status: "Issued",
    trades: ["Glass & Glazing"],
    gcContact: {
      companyName: "Lendlease",
      contactName: "Rachel Kim",
      phone: "(312) 555-0589",
      email: "rkim@lendlease.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(5),
  },
  {
    id: "p-009",
    permitNumber: "BLD-2026-041134",
    address: "77 W Wacker Dr",
    city: "Chicago",
    state: "IL",
    zip: "60601",
    latitude: 41.8867,
    longitude: -87.6316,
    filingDate: daysAgo(7),
    description:
      "Demolition of interior partitions and ceilings floors 4-6 for tenant improvement. Includes hazmat abatement and structural modifications.",
    estimatedValue: 520000,
    status: "Issued",
    trades: ["Demolition", "General Construction"],
    gcContact: {
      companyName: "Skender Construction",
      contactName: null,
      phone: "(312) 555-0612",
      email: "info@skender.com",
      confidence: "Low",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(6),
  },
  {
    id: "p-010",
    permitNumber: "BLD-2026-041098",
    address: "500 W Monroe St",
    city: "Chicago",
    state: "IL",
    zip: "60661",
    latitude: 41.8804,
    longitude: -87.6395,
    filingDate: daysAgo(7),
    description:
      "New concrete parking structure, 4 levels, approximately 320 spaces. Includes electrical for EV charging stations and fire suppression throughout.",
    estimatedValue: 8500000,
    status: "Under Review",
    trades: ["Concrete", "Electrical", "Fire Suppression"],
    gcContact: {
      companyName: "Walsh Construction",
      contactName: "Brian O'Malley",
      phone: "(312) 555-0678",
      email: "bomalley@walshgroup.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(7),
  },
  {
    id: "p-011",
    permitNumber: "BLD-2026-041056",
    address: "200 E Randolph St",
    city: "Chicago",
    state: "IL",
    zip: "60601",
    latitude: 41.8851,
    longitude: -87.6216,
    filingDate: daysAgo(8),
    description:
      "Plumbing renovation for hotel floors 8-14. Replace domestic water risers, waste stacks, and fixture rough-in for 120 guest rooms.",
    estimatedValue: 1680000,
    status: "Issued",
    trades: ["Plumbing"],
    gcContact: {
      companyName: "Mortenson Construction",
      contactName: "Lisa Tran",
      phone: "(312) 555-0734",
      email: "ltran@mortenson.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(7),
  },
  {
    id: "p-012",
    permitNumber: "BLD-2026-040998",
    address: "444 N Michigan Ave",
    city: "Chicago",
    state: "IL",
    zip: "60611",
    latitude: 41.8912,
    longitude: -87.6244,
    filingDate: daysAgo(9),
    description:
      "Rooftop solar panel installation and electrical tie-in for 20-story office building. 280kW system with inverters and monitoring.",
    estimatedValue: 950000,
    status: "Approved",
    trades: ["Electrical", "Roofing"],
    gcContact: {
      companyName: "Gilbane Building Company",
      contactName: "Mark Johanssen",
      phone: "(312) 555-0801",
      email: "mjohanssen@gilbane.com",
      confidence: "Medium",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(8),
  },
  {
    id: "p-013",
    permitNumber: "BLD-2026-040945",
    address: "151 N Franklin St",
    city: "Chicago",
    state: "IL",
    zip: "60606",
    latitude: 41.8843,
    longitude: -87.6355,
    filingDate: daysAgo(9),
    description:
      "New ground-floor retail buildout, 8,500 SF. Complete mechanical, electrical, and plumbing. Storefront glass installation.",
    estimatedValue: 1100000,
    status: "Issued",
    trades: ["HVAC", "Electrical", "Plumbing", "Glass & Glazing"],
    gcContact: {
      companyName: "Clune Construction",
      contactName: "Patrick Doyle",
      phone: "(312) 555-0867",
      email: "pdoyle@clune.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(9),
  },
  {
    id: "p-014",
    permitNumber: "BLD-2026-040889",
    address: "180 N Stetson Ave",
    city: "Chicago",
    state: "IL",
    zip: "60601",
    latitude: 41.8857,
    longitude: -87.6218,
    filingDate: daysAgo(10),
    description:
      "Emergency generator replacement and transfer switch upgrade. 2000kW diesel generator with fuel storage and exhaust system.",
    estimatedValue: 780000,
    status: "Issued",
    trades: ["Electrical"],
    gcContact: {
      companyName: "McHugh Construction",
      contactName: "Steve McHugh",
      phone: "(312) 555-0923",
      email: null,
      confidence: "Medium",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(9),
  },
  {
    id: "p-015",
    permitNumber: "BLD-2026-040834",
    address: "353 N Clark St",
    city: "Chicago",
    state: "IL",
    zip: "60654",
    latitude: 41.8887,
    longitude: -87.6311,
    filingDate: daysAgo(11),
    description:
      "Full-building fire alarm system replacement. New addressable panels, notification appliances, and duct detectors for 25-story office tower.",
    estimatedValue: 920000,
    status: "Approved",
    trades: ["Fire Suppression", "Electrical"],
    gcContact: {
      companyName: "Barton Malow",
      contactName: "Jennifer Wu",
      phone: "(312) 555-0989",
      email: "jwu@bartonmalow.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(10),
  },
  {
    id: "p-016",
    permitNumber: "BLD-2026-040778",
    address: "10 S LaSalle St",
    city: "Chicago",
    state: "IL",
    zip: "60603",
    latitude: 41.8817,
    longitude: -87.6322,
    filingDate: daysAgo(12),
    description:
      "Lobby renovation and new revolving door installation. Includes structural modifications, new marble flooring, and glass entry vestibule.",
    estimatedValue: 1350000,
    status: "Issued",
    trades: ["Glass & Glazing", "General Construction", "Structural Steel"],
    gcContact: {
      companyName: "Related Midwest",
      contactName: "Daniel Foster",
      phone: "(312) 555-1045",
      email: "dfoster@relatedmidwest.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(11),
  },
  {
    id: "p-017",
    permitNumber: "BLD-2026-040712",
    address: "600 W Chicago Ave",
    city: "Chicago",
    state: "IL",
    zip: "60654",
    latitude: 41.8965,
    longitude: -87.6445,
    filingDate: daysAgo(12),
    description:
      "Warehouse-to-office conversion, 45,000 SF. New HVAC systems, complete electrical distribution, plumbing for restrooms and break rooms, and sprinkler system.",
    estimatedValue: 6200000,
    status: "Under Review",
    trades: ["HVAC", "Electrical", "Plumbing", "Fire Suppression"],
    gcContact: {
      companyName: "Clayco",
      contactName: "Roberto Alvarez",
      phone: "(312) 555-1102",
      email: "ralvarez@claycorp.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(12),
  },
  {
    id: "p-018",
    permitNumber: "BLD-2026-040656",
    address: "875 N Michigan Ave",
    city: "Chicago",
    state: "IL",
    zip: "60611",
    latitude: 41.8987,
    longitude: -87.6239,
    filingDate: daysAgo(13),
    description:
      "Concrete repair and waterproofing for below-grade parking levels. Structural crack injection, membrane application, and sump pump replacement.",
    estimatedValue: 440000,
    status: "Issued",
    trades: ["Concrete", "Plumbing"],
    gcContact: {
      companyName: "Wiss Janney Elstner",
      contactName: null,
      phone: "(312) 555-1158",
      email: null,
      confidence: "Low",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(12),
  },
  {
    id: "p-019",
    permitNumber: "BLD-2026-040601",
    address: "321 N Clark St",
    city: "Chicago",
    state: "IL",
    zip: "60654",
    latitude: 41.8883,
    longitude: -87.6312,
    filingDate: daysAgo(13),
    description:
      "Data center buildout, 12,000 SF. Precision cooling, redundant electrical systems, raised floor, and fire suppression (clean agent).",
    estimatedValue: 4800000,
    status: "Issued",
    trades: ["HVAC", "Electrical", "Fire Suppression"],
    gcContact: {
      companyName: "Holder Construction",
      contactName: "Chris Nakamura",
      phone: "(312) 555-1214",
      email: "cnakamura@holderconstruction.com",
      confidence: "High",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(13),
  },
  {
    id: "p-020",
    permitNumber: "BLD-2026-040545",
    address: "111 S Michigan Ave",
    city: "Chicago",
    state: "IL",
    zip: "60603",
    latitude: 41.8801,
    longitude: -87.6245,
    filingDate: daysAgo(14),
    description:
      "Historic window replacement program, 450 windows. Custom-fabricated insulated glass units matching original profiles.",
    estimatedValue: 1900000,
    status: "Approved",
    trades: ["Glass & Glazing"],
    gcContact: {
      companyName: "Berglund Construction",
      contactName: "Anna Lindqvist",
      phone: "(312) 555-1270",
      email: "alindqvist@berglund.com",
      confidence: "Medium",
    },
    source: "data.cityofchicago.org",
    sourceUpdatedAt: daysAgo(13),
  },
];

export function formatCurrency(value: number): string {
  if (value >= 1_000_000) {
    return `$${(value / 1_000_000).toFixed(1)}M`;
  }
  if (value >= 1_000) {
    return `$${(value / 1_000).toFixed(0)}K`;
  }
  return `$${value.toLocaleString()}`;
}

export function formatFullCurrency(value: number): string {
  return new Intl.NumberFormat("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  }).format(value);
}
